Roomscout/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import TemplateView

from blog.sitemaps import BlogSitemap
from houses.sitemaps import HouseSitemap
from main.sitemaps import StaticSitemap
from rooms.sitemaps import RoomSitemap

sitemaps = {
    'static': StaticSitemap,
    'blog': BlogSitemap,
    'houses': HouseSitemap,
    'rooms': RoomSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots/robots.txt", content_type='text/plain')),
    path('', include('main.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler403 = 'main.views.permission_denied'
handler404 = 'main.views.page_not_found'
handler500 = 'main.views.server_error'

admin.site.site_header = "Roomscout Admin"
admin.site.site_title = "Roomscout Admin Portal"
admin.site.index_title = "Welcome to Roomscout Admin Portal"

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog_home'),
    path('<str:pk>/', views.BlogDetailView.as_view(), name='blog_post'),
]

main/urls.py
from django.urls import path, include

from accounts.views import settings, preferences, verification, email_unsubscribe
from . import views

urlpatterns = [
    # Content Pages
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('features/bill', views.billfeatures, name='billfeatures'),
    path('features/verification', views.verificationfeatures, name='verificationfeatures'),
    path('supportus', views.supportus, name='supportus'),
    path('contactus', views.contactus, name='contactus'),
    path('licenses', views.licenses, name='licenses'),
    path('privacypolicy', views.privacypolicy, name='privacypolicy'),
    path('termsofuse', views.termsofuse, name='termsofuse'),
    path('dashboard', include('dashboard.urls')),
    path('sandbox', views.sandbox, name='sandbox'),

    # Blog
    path('blog/', include('blog.urls')),

    # Accounts
    path('accounts/', include('allauth.urls')),
    path('settings', settings, name='settings'),
    path('settings/preferences', preferences, name='settings_preferences'),
    path('settings/verification', verification, name='settings_verification'),
    path('settings/unsubscribe', email_unsubscribe, name='email_unsubscribe'),

    # Bills
    path('bill/', include('bills.urls')),
    # Houses
    path('house/', include('houses.urls')),
    # Rooms
    path('room/', include('rooms.urls')),
    # Garbage Day
    path('garbageday/', include('garbageday.urls')),
    # Marketing
    path('m/', include('marketing.urls')),
    # Payments
    path('payment/', include('payments.urls')),
    # Easter Eggs
    path('ee/', include('eggs.urls')),
    # Security
    path('security/', include('security.urls')),
]

main/models.py
from django.db import models

from security.models import IP


class ContactMessage(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    sender = models.EmailField(default='')
    subject = models.TextField(default='')
    message = models.TextField(default='')
    ip = models.ForeignKey(IP, on_delete=models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return "{} - {} - {}".format(self.created_at, self.sender, self.subject)

rooms/models.py
from django.db import models
from django.templatetags.static import static
from django.urls import reverse

from accounts.models import User
from houses.models import House
from utils.datetime import time_diff_display


class Room(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    house = models.ForeignKey(House, on_delete=models.CASCADE, related_name='house')

    price = models.DecimalField(max_digits=19, decimal_places=2, default=0.00)
    name = models.CharField(max_length=200, default='')
    description = models.TextField(default='')
    is_available = models.BooleanField(verbose_name='Available', default=True, help_text='Room is available')

    is_accessible = models.BooleanField(default=False, verbose_name="Accessible", help_text="House is accessible with ramp or elevator")
    open_to_students = models.BooleanField(default=True, help_text="Students are free to inquire about rooms at this house")
    pet_friendly = models.BooleanField(default=False, help_text="Pets are allowed")
    utilities_included = models.BooleanField(default=False, help_text="All utilities are included in the price of rent")
    parking = models.BooleanField(default=False, help_text="Parking spot is included or available")
    furnished = models.BooleanField(default=False, help_text="Room is furnished with at least a bed, mattress, and dresser")
    female_only = models.BooleanField(default=False, help_text="Only females are allowed to inquire")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('room_detail', args=[str(self.pk)])

    def get_time_difference_display(self):
        return time_diff_display(self.updated_at)

    def get_first_image(self):
        room_images = self.roomimage_set
        if room_images.count() > 0:
            return room_images.first().image.url

        house_images = self.house.houseimage_set
        if house_images.count() > 0:
            return house_images.first().image.url

        return static('logos/logo.PNG')


class Inquiry(models.Model):
    STATUS_CHOICES = [('O', 'Open'), ('D', 'Dismissed')]

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    message = models.TextField(default='')
    move_in_date = models.DateField(default='1997-11-04')
    status = models.CharField(choices=STATUS_CHOICES, default='O', max_length=3)


class RoomLike(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, redirect

from bills.forms import BillFormset
from emails.senders import send_contact_us_email
from security.helpers import get_IP
from security.models import IP
from utils.captcha import Captcha
from .models import ContactMessage


def home(request):
    return render(request, 'main/home.html')


def about(request):
    return render(request, 'main/about.html')


def contactus(request):
    captcha = Captcha()
    if request.method == 'POST':
        ip_address = get_IP(request)
        ip = IP()
        ip.address = ip_address
        ip.save()

        send_contact_us_email(request.POST['sender_email'], request.POST['subject'], request.POST['message'], ip)
        message = ContactMessage()
        message.sender = request.POST['sender_email']
        message.subject = request.POST['subject']
        message.message = request.POST['message']
        message.ip = ip
        message.save()
        messages.success(request, 'We have received your contact request and will get back to you as soon as possible!')
        return redirect('home')
    return render(request, 'main/contactus.html', {'captcha': captcha})


def billfeatures(request):
    return render(request, 'main/billfeatures.html')


def supportus(request):
    key = settings.STRIPE_KEY
    return render(request, 'main/supportus.html', {'key': key})


def verificationfeatures(request):
    return render(request, 'main/verificationfeatures.html')


def licenses(request):
    return render(request, 'main/licenses.html')


def privacypolicy(request):
    return render(request, 'main/privacypolicy.html')


def termsofuse(request):
    return render(request, 'main/termsofuse.html')


def permission_denied(request, exception):
    return render(request, 'main/403.html')


def page_not_found(request, exception):
    return render(request, 'main/404.html')


def server_error(request):
    return render(request, 'main/500.html')


@staff_member_required(login_url="account_login")
def sandbox(request):
    if request.method == 'POST':
        print(request.POST)
        formset = BillFormset(request.POST)
        if formset.is_valid():
            for form in formset:
                print(form.cleaned_data)
        else:
            print('invalid')
    formset = BillFormset()
    return render(request, 'main/sandbox.html', {'formset': formset})

main/templates/main/_base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RoomScout - {% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Aaron Spindler">
    <link rel="shortcut icon" type="image/png" href="{% static 'logos/favicon.PNG' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" media="screen"/>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'open-iconic/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-100881995-5"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());
        gtag('config', 'UA-100881995-5');
    </script>
</head>

<body>
<header>
    {% block header %}
        {% include "main/_header.html" %}
    {% endblock %}
</header>

<main role="main">
    {% if messages %}
        <div class="text-center">
            <ul style="list-style: none" class="bg-success messages">
                {% for message in messages %}
                    <li>
                        {% if message.tags == 'success' %}
                            {{ message }}
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
    {% endif %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/fingerprintjs2/dist/fingerprint2.min.js"></script>
    <script>
        if (window.requestIdleCallback) {
            requestIdleCallback(function () {
                Fingerprint2.get(function (components) {
                    const values = components.map(function (component) {
                        return component.value
                    })
                    const murmur = Fingerprint2.x64hash128(values.join(''), 31)
                    $.ajax({
                        type: "POST",
                        url: "{% url 'security_fingerprint_save' %}",
                        headers: {'X-CSRFToken': '{{ csrf_token }}'},
                        data: {
                            'murmur': murmur
                        },
                        success: function () {
                        }
                    });
                })
            })
        } else {
            setTimeout(function () {
                Fingerprint2.get(function (components) {
                    const values = components.map(function (component) {
                        return component.value
                    })
                    const murmur = Fingerprint2.x64hash128(values.join(''), 31)
                    $.ajax({
                        type: "POST",
                        url: "{% url 'security_fingerprint_save' %}",
                        headers: {'X-CSRFToken': '{{ csrf_token }}'},
                        data: {
                            'murmur': murmur
                        },
                        success: function () {
                        }
                    });
                })
            }, 500)
        }
    </script>

    {% block content %}

    {% endblock %}
</main>

<footer>
    {% include "main/_footer.html" %}
</footer>
</body>
</html>

main/templates/main/_footer.html
{% load static %}
<hr>
<div class="container py-5">
    <div class="row">
        <div class="col-12 col-md">
            <img class="img-fluid" src="{% static 'logos/logo.PNG' %}" width="45" height="45">
            <small class="d-block mb-3 text-muted">&copy; {% now "Y" %}</small>
        </div>
        <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'billfeatures' %}">Bill Features</a></li>
                <li><a class="text-muted" href="{% url 'verificationfeatures' %}">Verification Features</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Company</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'supportus' %}">Support Us</a></li>
                <li><a class="text-muted" href="{% url 'about' %}">About</a></li>
                <li><a class="text-muted" href="{% url 'blog_home' %}">Blog</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Support</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'contactus' %}">Contact Us</a></li>
                <li><a class="text-muted" href="{% url 'privacypolicy' %}">Privacy Policy</a></li>
                <li><a class="text-muted" href="{% url 'termsofuse' %}">Terms of Use</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Community</h5>
            <ul class="list-unstyled text-small">
                <a class="text-muted" href="https://www.linkedin.com/company/roomscout-ca/"><img width="20" src="{% static 'logos/linkedin.png' %}"></a>
                <a class="text-muted" href="https://twitter.com/room_scout/"><img width="20" src="{% static 'logos/twitter.png' %}"></a>
                <a class="text-muted" href="https://www.instagram.com/room.scout/"><img width="20" src="{% static 'logos/instagram.png' %}"></a>
                <a class="text-muted" href="https://www.github.com/xNovax/Roomscout"><img width="20" src="{% static 'logos/github.png' %}"></a>
            </ul>
        </div>
    </div>
</div>
<hr>

main/templates/main/_header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark indigo fixed-top text-white">
    
    <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'logos/logo.PNG' %}" height=35 width=35> RoomScout</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link p-2" href="{% url 'room_create' %}">Post Room</a>
            </li>
            <li class="nav-item">
                <a class="nav-link p-2" href="{% url 'room_list' %}">Find Room</a>
            </li>

            {% if user.is_superuser %}
            {% endif %}

            {% if user.is_authenticated %}
            {% endif %}
        </ul>
        {% if user.is_authenticated == False %}
            <a class="btn btn-outline-white mx-2" href="{% url 'account_login' %}">Log In <span class="oi oi-account-login"></span></a>
            <a class="btn btn-outline-white mx-2" href="{% url 'account_signup' %}">Sign up</a>
        {% else %}
            <a class="p-2 text-white nav-item nav-link" href="{% url 'main_dashboard' %}">Dashboard <span class="oi oi-home"></span></a>
            <a class="p-2 text-white nav-item nav-link" href="{% url 'settings' %}">Settings <span class="oi oi-cog"></span></a>
            <small>Logged in as : {{ user }} {% if user.is_premium_member %}<a href="#" class="badge badge-warning">Premium</a>{% endif %} 
                <a class="p-2 text-white nav-item" href="{% url 'account_logout' %}"> Logout</a></small>
        {% endif %}
    </div>
</nav>

main/templates/main/about.html
{% extends 'main/_base.html' %}
{% load static %}

{% block title %}
    About Us
{% endblock %}

{% block content %}

<div class="row container-fluid">
    
    <div class="col-lg-2"></div>

    <div class="col-lg-7">
        <div class="container">
            <h2 class="h2">About Us</h2>
            <hr>
            <p>RoomScout.ca was started as a little side project to help get rid of a problem that I was facing. The problem I was facing was that I was managing bills for a house that I had with a
                spreadsheet, and it became tedious to add bills and then send a spreadsheet to my tenants every month. I also had an issue of getting a new tenant when my current one had left without
                notice.</p>
            <p>I decided that I can start a project that would help solve my problems and also teach me a little about web development.</p>
            <p>If there are any bugs or issues that you face, feel free to email me personally at <a href="mailto:aaron@xnovax.net">Aaron@xNovax.net</a>, I am happy to help and hope that this project can
                grow to help others that are looking for an easier way to manage roommates.</p>
        </div>
    </div>

    <div class="col-lg-3"></div>
</div>

{% endblock %}

main/templates/main/billfeatures.html
{% extends 'main/_base.html' %}
{% load static %}

{% block title %}
    Bill Features
{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="h2">Bill Features</h2>
        <hr>
        <div class="row featurette">
            <div class="col-md-7 order-md-2">
                <h4 class="h4 featurette-heading">Bill Learning<span class="text-muted"> Submit more data so more insights can be generated</span></h4>
                <p class="lead">Bills are analyzed each month to provide useful insights such as bill predictions</p>
            </div>
            <div class="col-md-5 order-md-1">
                <img class="img-fluid" width="500" src="{% static 'main/billgraph.png' %}">
            </div>
        </div>

        <br>
        <hr>
        <div class="row featurette">
            <div class="col-md-7">
                <h4 class="featurette-heading h4">Bill Organization <span class="text-muted">Keep your life organized</span></h4>
                <p class="lead">Keep on top of your bills and make sure that they are paid. Roomscout will automatically notify house members when a new bill is added. Pick between notifying roommates when a bill is added or notifying at the end of the month.</p>
            </div>
            <div class="col-md-5">
                <img class="img-fluid" width="500" src="{% static 'main/billorganization.png' %}">
            </div>
        </div>

        <br>
    </div>
{% endblock %}

main/templates/main/contactus.html
{% extends 'main/_base.html' %}
{% load static %}

{% block title %}
    Contact Us
{% endblock %}

{% block content %}
<div class="row container-fluid">
    
    <div class="col-lg-2"></div>
    
        <div class="col-lg-7">
            <div class="container">
                <h2 class="h2">Contact Us</h2>
                <hr>
                <form method="POST">
                        {% csrf_token %}
                        {{ captcha }}
                        <input class="form-control" type="email" name="sender_email" placeholder="Your email" required>
                        <br>
                        <input class="form-control" type="text" name="subject" placeholder="Subject" required>
                        <br>
                        <textarea class="form-control" rows="10" placeholder="Message: Maybe you want to talk to us about the weather or something you think we should add?" name="message" required></textarea>
                        <br>
                        <button class="btn btn-primary" type='submit'>Send</button>
                    </form>
            </div>
        </div>
    
    <div class="col-lg-3"></div>
</div>
    
{% endblock %}

main/templates/main/home.html
{% extends 'main/_base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
     <!--Carousel Wrapper-->
     <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
          <li data-target="#myCarousel" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner">
          <div class="carousel-item active">
              <svg class="bd-placeholder-img" width="100%" height="60vh" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false"
                   role="img">
                  <rect width="100%" height="100%" fill="#7472DF"></rect>
              </svg>
              <div class="container">
                  <div class="carousel-caption flex-center">
                    <ul class="animated fadeInUp col-md-12 list-unstyled list-inline">
                      <li>
                        <h1 class="font-weight-bold text-uppercase">Find the perfect roommate!</h1>
                      </li>
                      <li>
                        <p class="font-weight-bold text-uppercase py-4">Roomscout helps you find the perfect roommate</p>
                      </li>
                      <li class="list-inline-item">
                          {% if user.is_authenticated %}
                          <p><a class="btn btn-lg btn-primary" href="{% url 'room_create' %}" role="button">Post your
                              room now!</a></p>
                      {% else %}
                          <p><a class="btn btn-lg btn-primary" href="{% url 'account_signup' %}" role="button">Sign up
                              today!</a>
                          </p>
                      {% endif %}
                      </li>
                    </ul>
                      
                  </div>
              </div>
          </div>
          <div class="carousel-item">
              <svg class="bd-placeholder-img" width="100%" height="60vh" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false"
                   role="img">
                  <rect width="100%" height="100%" fill="#7472DF"></rect>
              </svg>
              <div class="container">
                  <div class="carousel-caption flex-center">
                    <ul class="animated fadeInUp col-md-12 list-unstyled list-inline">
                      <li>
                          <h1 class="font-weight-bold text-uppercase">Find The Perfect Room</h1>
                      </li>
                      <li>
                          <p class="font-weight-bold text-uppercase py-4">Find the perfect place to live and the best roommates to live with!</p>
                      </li>
                      <li class="list-inline-item">
                          <p><a class="btn btn-lg btn-primary" href="{% url 'room_list' %}" role="button">Search Now!</a>
                      </li>
                  </ul>
                  </div>
              </div>
          </div>
          <div class="carousel-item">
              <svg class="bd-placeholder-img" width="100%" height="60vh" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false"
                   role="img">
                  <rect width="100%" height="100%" fill="#7472DF"></rect>
              </svg>
              <div class="container">
                  <div class="carousel-caption flex-center">
                    <ul class="animated fadeInUp col-md-12 list-unstyled list-inline">
                      <li>
                          <h1 class="font-weight-bold text-uppercase">Manage Bills</h1>
                      </li>
                      <li>
                          <p class="font-weight-bold text-uppercase py-4">Manage household utility bills, splitting of bills, and gain insight into your future bills</p>
                      </li>
                      <li class="list-inline-item">
                          <p><a class="btn btn-lg btn-primary" href="{% url 'billfeatures' %}" role="button">See it in action!</a></p>
                      </li>
                  </ul>
                  </div>
              </div>
          </div>
          <div class="carousel-item">
              <svg class="bd-placeholder-img" width="100%" height="60vh" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false"
                   role="img">
                  <rect width="100%" height="100%" fill="#7472DF"></rect>
              </svg>
              <div class="container">
                  <div class="carousel-caption flex-center">
                    <ul class="animated fadeInUp col-md-12 list-unstyled list-inline">
                      <li>
                          <h1 class="font-weight-bold text-uppercase">Verify and Vet Prospective Roommates</h1>
                      </li>
                      <li>
                          <p class="font-weight-bold text-uppercase py-4">Using advanced technology RoomScout allows you to vet prospective roommates based on more than just their credit score</p>
                      </li>
                      <li class="list-inline-item">
                              <p><a class="btn btn-lg btn-primary" href="{% url 'verificationfeatures' %}" role="button">Learn More!</a></p>
                      </li>
                  </ul>
                  </div>
              </div>
          </div>
      </div>
      <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
      </a>
  </div>
  <!--/.Carousel Wrapper-->
    <br>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    <div class="container-fluid marketing">
        <!-- START THE FEATURETTES -->
        <div class="row featurette pl-4 ml-4 pb-4 mb-4 pt-2 mt-4 mr-4">
            <div class="col-md-7">
                <h2 class="featurette-heading">Looking for someone to move in?<span class="text-muted"> Post your room now</span></h2>
                <p class="lead">If you are looking for a roommate to live in your house or someone to split an apartment
                    with. Look no further, post your available room on RoomScout</p>
                <a class="btn btn-lg btn-primary" href="{% url 'room_create' %}">Post Now</a>
            </div>
            <div class="col-md-5">
                <img class="img-fluid pt-2" src="{% static 'stock_photos/tenant_2.jpg' %}" width=400/>
            </div>
        </div>
    </div>

    <div class="container-fluid text-white bg-primary">

        <div class="row pl-4 ml-4 pb-4 mb-4 pt-5 mt-5 mr-4">
                <div class="col-md-5">
                    <img class="img-fluid" src="{% static 'stock_photos/bedroom_2.jpg' %}" width=400/>
                </div>

            <div class="col-md-7">
                <h2 class="featurette-heading">Looking for a place to live?<span class="amber-text"> Find the perfect room!</span>
                </h2>
                <p class="lead">Are you looking for the perfect place to live but are not ready to live alone? Find the
                    perfect place by search rooms on RoomScout</p>
                <a class="btn btn-lg btn-outline-white waves-effect" href="{% url 'room_list' %}">Start your search</a>
            </div>
            
        </div>
    </div>
    <div class="container-fluid">

        <div class="row featurette pl-4 ml-4 pb-4 mb-4 pt-4 mt-4 mr-4">
            <div class="col-md-7">
                <h2 class="featurette-heading">And lastly, <span class="text-muted"> take the headache out of managing shared expenses</span>
                </h2>
                <p class="lead">Do you split utilities with the other people living in your house / apartment? If so it
                    can be a huge burden to manage expenses and make sure you get paid. RoomScout relieves that headache
                    by splitting and managing it all for you.</p>
            </div>
            <div class="col-md-5">
                <img class="img-fluid" src="{% static 'stock_photos/finances_1.jpg' %}" width=400/></div>
        </div>
        <!-- /END THE FEATURETTES -->

    </div><!-- /.container -->
{% endblock %}

main/templates/main/licenses.html
{% extends 'main/_base.html' %}
{% load static %}

{% block title %}
    Licenses
{% endblock %}

{% block content %}
<div class="row container-fluid">
    
    <div class="col-lg-2"></div>

    <div class="col-lg-7">
        <div class="container">
            <h2 class="h2">Licenses</h2>
            <hr>
            <p></p>
        </div>
    </div>

    <div class="col-lg-3"></div>
</div>


{% endblock %}

main/templates/main/termsandconditons.html
{% extends 'main/_base.html' %}
{% load staticfiles %}

{% block title %}
    Terms and Conditions
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Terms and Conditions</h2>
    </div>

{% endblock %}

main/templates/main/verificationfeatures.html
{% extends 'main/_base.html' %}
{% load static %}

{% block title %}
    Verification Features
{% endblock %}

{% block content %}
<div class="row container-fluid">
    
        <div class="col-lg-2"></div>
    
        <div class="col-lg-7">
            <div class="container">
                <h2 class="h2">Verification Features</h2>
                <hr>
                <h4>Coming Soon</h4>
            </div>
        </div>
    
        <div class="col-lg-3"></div>
    </div>
{% endblock %}